import i18next from "i18next";
import { useTranslation } from "react-i18next";

const useDatabaseColumns = () => {
  const { t } = useTranslation();
  return {
    users: {
      title: t("user_management"),
      headers: [
        t("id"),
        t("profile_picture"),
        t("first_name"),
        t("last_name"),
        t("username"),
        t("email"),
        t("phone_number"),
        t("city"),
        t("blocked"),
        t("verified"),
        t("sports"),
        t("role"),
      ],
      fields: [
        "id",
        "profile_picture",
        "first_name",
        "last_name",
        "username",
        "email",
        "phone_number",
        "city",
        "blocked",
        "verified",
        "sport",
        "role",
      ],
    },
    venues: {
      title: t("venue_management"),
      headers: [
        t("id"),
        t("venue_picture"),
        t("name_3"),
        t("address"),
        t("city"),
        t("type"),
        t("description"),
        t("price_per_hour"),
        t("opening_time"),
        t("closing_time"),
        t("company"),
        t("sport"),
      ],
      fields: [
        "id",
        "venue_picture",
        "venue_name",
        "address",
        "city",
        "type",
        "description",
        "price_per_hour",
        "opening_time",
        "closing_time",
        "company",
        "sport",
      ],
    },
    sports: {
      title: t("sports_management"),
      headers: [t("id"), t("sport_name")],
      fields: ["id", "sport_name"],
    },
    reservations: {
      title: t("reservations_management"),
      headers: [
        t("id"),
        t("user"),
        t("venue"),
        t("sports"),
        t("total_places"),
        t("going"),
        t("start_time"),
        t("end_time"),
        t("description"),
        t("approved"),
        t("auto_invite"),
        t("number_of_invites"),
      ],
      fields: [
        "id",
        "user",
        "venue",
        "sport",

        "total_places",
        "going",
        "start_time",
        "end_time",
        "description",
        "approved",
        "auto_invite",
        "number_of_invites",
      ],
    },
    acceptedinvites: {
      title: t("accepted_invites_management"),
      headers: [t("id"), t("reservation"), t("user")],
      fields: ["id", "reservation", "user"],
    },
    questions: {
      title: t("question_management"),
      headers: [t("id"), t("text"), t("answer"), t("pinned")],
      fields: ["id", "text", "answer", "pinned"],
    },
    ratings: {
      title: t("rating_management"),
      headers: [t("id"), t("rating"), t("user"), t("venue")],
      fields: ["id", "rating", "user", "venue"],
    },
    verification: {
      title: t("company_verification"),
      headers: [
        t("id"),
        t("first_name"),
        t("last_name"),
        t("username"),
        t("email"),
        t("phone_number"),
        t("city"),
        t("blocked"),
        t("sports"),
      ],
      fields: [
        "id",
        "first_name",
        "last_name",
        "username",
        "email",
        "phone_number",
        "city",
        "blocked",
        "sport",
      ],
    },
  };
};

export default useDatabaseColumns;
