# Generated by Django 4.1.4 on 2023-05-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='venue_picture',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
