# Generated by Django 4.1.4 on 2023-05-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0002_alter_question_answer_alter_venue_venue_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='city',
            field=models.CharField(max_length=50),
        ),
    ]
