# Generated by Django 4.1.4 on 2023-06-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venue", "0003_alter_venue_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="closing_time",
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name="venue",
            name="opening_time",
            field=models.CharField(max_length=5),
        ),
    ]
