# Generated by Django 4.1.4 on 2023-06-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venue", "0004_alter_venue_closing_time_alter_venue_opening_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="type",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
