# Generated by Django 4.1.4 on 2023-06-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venue", "0005_alter_venue_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="venue_picture",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
