# Generated by Django 4.1.4 on 2023-05-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acceptedinvites',
            old_name='reservation_id',
            new_name='reservation',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='approved',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='number_of_invites',
            field=models.IntegerField(blank=True),
        ),
    ]
