# Generated by Django 4.1.4 on 2023-06-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reservation",
            "0002_rename_reservation_id_acceptedinvites_reservation_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="approved",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="end_time",
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="start_time",
            field=models.CharField(max_length=5),
        ),
    ]
