# Generated by Django 4.1.4 on 2023-06-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0003_alter_reservation_approved_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="number_of_invites",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
