# Generated by Django 4.1.4 on 2023-06-15 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_alter_reservation_end_time_and_more'),
        ('reservation', '0004_alter_reservation_number_of_invites'),
    ]

    operations = [
    ]
