# Generated by Django 4.1.4 on 2023-05-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='blocked',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Admin'), (2, 'User'), (3, 'Company')], default=2, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sport',
            field=models.ManyToManyField(blank=True, to='user.sport'),
        ),
        migrations.AlterField(
            model_name='user',
            name='verified',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
