# Generated by Django 4.1.4 on 2023-05-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sport',
            field=models.ManyToManyField(blank=True, to='user.sport'),
        ),
    ]
