# Generated by Django 4.1.4 on 2023-06-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_alter_user_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="verified",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
