# Generated by Django 4.1.4 on 2023-06-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_alter_user_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="verified",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
