# Generated by Django 4.1.4 on 2023-06-04 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_remove_user_is_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_superuser",
        ),
    ]
