# Generated by Django 4.1.4 on 2023-06-11 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_alter_user_company_name"),
        ("user", "0012_remove_user_is_active"),
    ]

    operations = []
