# Generated by Django 4.1.4 on 2023-06-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0014_user_is_active_user_is_staff_user_is_superuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=255),
        ),
    ]
