# Generated by Django 4.1.4 on 2023-06-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0016_user_created_at_user_deleted_at_user_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="company_name",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
