# Generated by Django 4.1.4 on 2023-06-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0017_alter_user_company_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.CharField(
                blank=True,
                default="https://firebasestorage.googleapis.com/v0/b/sportify-4db02.appspot.com/o/files%2Fdefault_profile_picture.jpg?alt=media&token=146819b8-b4ca-40b3-a308-1db7b0d4306e",
                max_length=255,
            ),
        ),
    ]
