# Generated by Django 4.1.4 on 2023-05-15 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venueapp', '0001_initial'),
        ('authapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_places', models.IntegerField()),
                ('going', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('description', models.CharField(max_length=255)),
                ('approved', models.BooleanField(default=False)),
                ('auto_invite', models.BooleanField(default=False)),
                ('number_of_invites', models.IntegerField()),
                ('sport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.sport')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('venue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venueapp.venue')),
            ],
        ),
        migrations.CreateModel(
            name='AcceptedInvites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservationapp.reservation')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
